### ISSUE TITLE
virtual board numpy 13 cast error

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker8#27]
Only when running using virtual board and numpy 13 (not checked if also a pynn7 issue)

https://github.com/SpiNNakerManchester/sPyNNaker8/blob/more_integration_tests/unittests/test_integration_using_virtual_baord/test_synfire_posson_if_curr_exp_parameter_test_second_none.py

File "/brenninc/spinnaker/sPyNNaker/spynnaker/pyNN/models/neuron/synapse_io/synapse_io_row_based.py", line 318, in read_synapses
    delayed_connections["source"] -= connection_source_extra
TypeError: Cannot cast ufunc subtract output from dtype('int64') to dtype('uint32') with casting rule 'same_kind'

2017-06-27 16:48:30 ERROR: Error when calling spynnaker.pyNN.overridden_pacman_functions.spynnaker_data_specification_writer.SpynnakerDataSpecificationWriter.__call__ with inputs {'report_default_directory': '/brenninc/spinnaker/my_spinnaker/reports/reports/2017-06-27-16-48-30-177380/run_1', 'write_text_specs': False, 'machine': [VirtualMachine: max_x=7, max_y=7], 'app_data_runtime_folder': '/brenninc/spinnaker/my_spinnaker/application_generated_data_files/2017-06-27-16-48-30-177380/run_1', 'graph_mapper': <pacman.model.graphs.common.graph_mapper.GraphMapper object at 0x7fd061212db8>, 'graph': <pacman.model.graphs.machine.machine_graph.MachineGraph object at 0x7fd06123dc20>, 'hostname': 'virtual', 'placements': (0, 0, 5)(0, 0, 1)(0, 0, 2)(0, 0, 3)(0, 0, 4)}

Error
Traceback (most recent call last):
  File "/brenninc/spinnaker/sPyNNaker8/unittests/test_integration_using_virtual_baord/test_synfire_posson_if_curr_exp_parameter_test_second_none.py", line 36, in test_synfire_posson_if_curr_exp_parameter_test_second_none
    record_input_spikes=record_input_spikes)
  File "/brenninc/spinnaker/sPyNNaker8/p8_integration_tests/scripts/synfire_run.py", line 339, in do_run
    p.run(runtime)
  File "/brenninc/spinnaker/sPyNNaker8/spynnaker8/__init__.py", line 479, in run
    return __pynn_run(simtime, callbacks=callbacks)
  File "/home/M04/acs/brenninc/pynn8_numpy13/lib/python2.7/site-packages/pyNN/common/control.py", line 110, in run
    return run_until(simulator.state.t + simtime, callbacks)
  File "/home/M04/acs/brenninc/pynn8_numpy13/lib/python2.7/site-packages/pyNN/common/control.py", line 92, in run_until
    simulator.state.run_until(time_point)
  File "/brenninc/spinnaker/sPyNNaker8/spynnaker8/spinnaker.py", line 123, in run_until
    self._run(tstop - self._current_run_timesteps)
  File "/brenninc/spinnaker/sPyNNaker8/spynnaker8/spinnaker.py", line 168, in _run
    AbstractSpiNNakerCommon.run(self, duration_ms)
  File "/brenninc/spinnaker/sPyNNaker/spynnaker/pyNN/abstract_spinnaker_common.py", line 326, in run
    AbstractSpinnakerBase.run(self, run_time)
  File "/brenninc/spinnaker/SpiNNFrontEndCommon/spinn_front_end_common/interface/abstract_spinnaker_base.py", line 715, in run
    self._do_data_generation(steps[0])
  File "/brenninc/spinnaker/SpiNNFrontEndCommon/spinn_front_end_common/interface/abstract_spinnaker_base.py", line 1323, in _do_data_generation
    executor = self._run_algorithms(inputs, algorithms, outputs)
  File "/brenninc/spinnaker/SpiNNFrontEndCommon/spinn_front_end_common/interface/abstract_spinnaker_base.py", line 885, in _run_algorithms
    executor.execute_mapping()
  File "/brenninc/spinnaker/PACMAN/pacman/executor/pacman_algorithm_executor.py", line 422, in execute_mapping
    self._execute_mapping()
  File "/brenninc/spinnaker/PACMAN/pacman/executor/pacman_algorithm_executor.py", line 438, in _execute_mapping
    results = algorithm.call(self._internal_type_mapping)
  File "/brenninc/spinnaker/PACMAN/pacman/executor/algorithm_classes/abstract_python_algorithm.py", line 45, in call
    results = self.call_python(method_inputs)
  File "/brenninc/spinnaker/PACMAN/pacman/executor/algorithm_classes/python_class_algorithm.py", line 57, in call_python
    return method(**inputs)
  File "/brenninc/spinnaker/sPyNNaker/spynnaker/pyNN/overridden_pacman_functions/spynnaker_data_specification_writer.py", line 45, in __call__
    app_data_runtime_folder, machine)
  File "/brenninc/spinnaker/SpiNNFrontEndCommon/spinn_front_end_common/interface/interface_functions/front_end_common_graph_data_specification_writer.py", line 111, in _generate_data_spec_for_vertices
    vertex.generate_data_specification(spec, placement)
  File "/brenninc/spinnaker/PACMAN/pacman/executor/injection_decorator.py", line 119, in wrapper
    return wrapped_method(obj, *args, **new_args)
  File "/brenninc/spinnaker/sPyNNaker/spynnaker/pyNN/models/neuron/abstract_population_vertex.py", line 590, in generate_data_specification
    self._input_type, machine_time_step)
  File "/brenninc/spinnaker/sPyNNaker/spynnaker/pyNN/models/neuron/synaptic_manager.py", line 794, in write_data_spec
    routing_info, graph_mapper, machine_graph, machine_time_step)
  File "/brenninc/spinnaker/sPyNNaker/spynnaker/pyNN/models/neuron/synaptic_manager.py", line 651, in _write_synaptic_matrix_and_master_population_table
    app_edge.n_delay_stages, machine_time_step)
  File "/brenninc/spinnaker/sPyNNaker/spynnaker/pyNN/models/neuron/synapse_io/synapse_io_row_based.py", line 318, in read_synapses
    delayed_connections["source"] -= connection_source_extra
TypeError: Cannot cast ufunc subtract output from dtype('int64') to dtype('uint32') with casting rule 'same_kind'

**Comment by Christian-B** [comment]
See: 
https://travis-ci.org/SpiNNakerManchester/sPyNNaker8/builds/247539984

**Comment by Christian-B** [comment]
Fixed with https://github.com/SpiNNakerManchester/sPyNNaker/pull/340
