### ISSUE TITLE
[Question] SpinnmanIOException "no such table" and "Invalid packet of type command_code"

### ISSUE THREAD

**Issue by bjuergens** [SpiNNakerManchester/sPyNNaker8#358]
I am investigating a bug in NRP's Spinnaker Integration. And two error message come up in relation to the bug I am investigating and I need to find out if these are red herrings, or if they are actually related to my bug. 

The errors are `SpinnmanIOException: IO Error: no such table: configuration_parameters` and 
`SpinnmanIOException: IO Error: Invalid packet of type command_code received: expected a pause/stop command code now, and did not receive it.`

In which cases can these errors appear? I suspect that it has something to do with an unclean shutdown of a previous session. 

Each error happens reproducibly just before the simulation starts (and after the brain has been loaded to the board). And after each error the simulation on the board seems to work (because NRP seems to receive plausible spikes from the board), but the changes to the rates of the PoissonSpikeGenerator from NRP don't seem to arrive at the SpiNNaker board. 

_________________________

The log for `Invalid packet` 

```[spinn_front_end_common.utilities.notification_protocol.notification_protocol][INFO] 2020-02-20 14:57:47,446: ** Confirmation from 127.0.0.1:52254 received, continuing **
Loading buffers
|0%                          50%                         100%|
 ============================================================
[spinn_front_end_common.utilities.notification_protocol.notification_protocol][INFO] 2020-02-20 14:57:47,495: ** Awaiting for a response from an external source to state its ready for the simulation to start **
[spinn_front_end_common.utilities.notification_protocol.notification_protocol][INFO] 2020-02-20 14:57:47,495: ** Sending start / resume message to external sources to state the simulation has started or resumed. **
[spinn_front_end_common.utilities.notification_protocol.notification_protocol][INFO] 2020-02-20 14:57:47,495: ** Awaiting for a response from an external source to state its ready for the simulation to start **
[spinn_front_end_common.utilities.database.database_connection][INFO] 2020-02-20 14:57:47,495: Waiting for message to indicate that the simulation has stopped or paused
[spinn_front_end_common.interface.interface_functions.application_runner][INFO] 2020-02-20 14:57:47,496: Application is set to run forever; exiting
[hbp_nrp_cle.brainsim.pynn_spiNNaker.devices.__PyNNSpiNNakerPoissonSpikeGenerator][INFO] 2020-02-20 14:57:47,496: Poisson Spike generator ready to reconfigure rates
[hbp_nrp_cle.brainsim.pynn_spiNNaker.devices.__PyNNSpiNNakerPoissonSpikeGenerator][INFO] 2020-02-20 14:57:47,496: Poisson Spike generator ready to reconfigure rates
[pacman.executor.pacman_algorithm_executor][INFO] 2020-02-20 14:57:47,497: Time 0:00:00.054821 taken by ApplicationRunner
Getting provenance data from machine graph
|0%                          50%                         100%|[spinn_front_end_common.utilities.database.database_connection][ERROR] 2020-02-20 14:57:47,497: Failure processing database callback
Traceback (most recent call last):
  File "/home/bjuergens/.opt/platform_venv/local/lib/python2.7/site-packages/spinn_front_end_common/utilities/database/database_connection.py", line 108, in __run
    self.__pause_stop()
  File "/home/bjuergens/.opt/platform_venv/local/lib/python2.7/site-packages/spinn_front_end_common/utilities/database/database_connection.py", line 157, in __pause_stop
    "receive it")
SpinnmanInvalidPacketException: Invalid packet of type command_code received: expected a pause/stop command code now, and did not receive it.

[hbp_nrp_cle.brainsim.pynn_spiNNaker.devices.__PyNNSpiNNakerPoissonSpikeGenerator][INFO] 2020-02-20 14:57:47,498: Poisson Spike generator ready to reconfigure rates
 [spinn_front_end_common.utilities.database.database_connection][INFO] 2020-02-20 14:57:47,498: Waiting for message to indicate that the simulation has stopped or paused
============Exception in thread SpyNNakerDatabaseConnection:0.0.0.0:38626:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/bjuergens/.opt/platform_venv/local/lib/python2.7/site-packages/spinn_front_end_common/utilities/database/database_connection.py", line 112, in __run
    raise_from(SpinnmanIOException(str(e)), e)
  File "/home/bjuergens/.opt/platform_venv/local/lib/python2.7/site-packages/six.py", line 738, in raise_from
    raise value
SpinnmanIOException: IO Error: Invalid packet of type command_code received: expected a pause/stop command code now, and did not receive it.
=
===============================================
Getting provenance data from application graph
|0%                          50%                         100%|
 ============================================================
[pacman.executor.pacman_algorithm_executor][INFO] 2020-02-20 14:57:47,501: Time 0:00:00.002423 taken by GraphProvenanceGatherer
[spinn_front_end_common.interface.abstract_spinnaker_base][INFO] 2020-02-20 14:57:47,502: Waiting for stop request
```
(note: debugging showed that expected package was 10 and the received package was 3074)

log output for `no such table`:

```
[spinn_front_end_common.utilities.notification_protocol.notification_protocol][INFO] 2020-02-20 15:01:37,099: ** Awaiting for a response from an external source to state its ready for the simulation to start **
[spinn_front_end_common.utilities.database.database_connection][INFO] 2020-02-20 15:01:37,099: Waiting for message to indicate that the simulation has stopped or paused
[spinn_front_end_common.interface.interface_functions.application_runner][INFO] 2020-02-20 15:01:37,100: Application is set to run forever; exiting
[hbp_nrp_cle.brainsim.pynn_spiNNaker.devices.__PyNNSpiNNakerPoissonSpikeGenerator][INFO] 2020-02-20 15:01:37,101: Poisson Spike generator ready to reconfigure rates
[hbp_nrp_cle.brainsim.pynn_spiNNaker.devices.__PyNNSpiNNakerPoissonSpikeGenerator][INFO] 2020-02-20 15:01:37,101: Poisson Spike generator ready to reconfigure rates
[pacman.executor.pacman_algorithm_executor][INFO] 2020-02-20 15:01:37,101: Time 0:00:00.057169 taken by ApplicationRunner
Getting provenance data from machine graph
|0%                          50%                         100%|[spinn_front_end_common.utilities.database.database_connection][INFO] 2020-02-20 15:01:37,102: 0.0.0.0:52525 Reading database

 [hbp_nrp_cle.brainsim.pynn_spiNNaker.devices.__PyNNSpiNNakerPoissonSpikeGenerator][INFO] 2020-02-20 15:01:37,102: Poisson Spike generator ready to reconfigure rates
===[spinn_front_end_common.utilities.database.database_connection][INFO] 2020-02-20 15:01:37,102: Waiting for message to indicate that the simulation has stopped or paused
=[spinn_front_end_common.utilities.database.database_connection][INFO] 2020-02-20 15:01:37,104: database is at 
=================================================[spinn_front_end_common.utilities.database.database_connection][ERROR] 2020-02-20 15:01:37,104: Failure processing database callback
Traceback (most recent call last):
  File "/home/bjuergens/.opt/platform_venv/local/lib/python2.7/site-packages/spinn_front_end_common/utilities/database/database_connection.py", line 100, in __run
    self.__read_db(address, data)
  File "/home/bjuergens/.opt/platform_venv/local/lib/python2.7/site-packages/spinn_front_end_common/utilities/database/database_connection.py", line 127, in __read_db
    db_callback(db_reader)
  File "/home/bjuergens/.opt/platform_venv/local/lib/python2.7/site-packages/spinn_front_end_common/utilities/connections/live_event_connection.py", line 244, in __read_database_callback
    "runtime")
  File "/home/bjuergens/.opt/platform_venv/local/lib/python2.7/site-packages/spinn_front_end_common/utilities/database/database_reader.py", line 186, in get_configuration_parameter_value
    " WHERE parameter_id = ?", parameter_name)
  File "/home/bjuergens/.opt/platform_venv/local/lib/python2.7/site-packages/spinn_front_end_common/utilities/database/database_reader.py", line 49, in __exec_one
    self._cursor.execute(query + " LIMIT 1", args)
OperationalError: no such table: configuration_parameters
======Exception in thread SpyNNakerDatabaseConnection:0.0.0.0:52525:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/bjuergens/.opt/platform_venv/local/lib/python2.7/site-packages/spinn_front_end_common/utilities/database/database_connection.py", line 112, in __run
    raise_from(SpinnmanIOException(str(e)), e)
  File "/home/bjuergens/.opt/platform_venv/local/lib/python2.7/site-packages/six.py", line 738, in raise_from
    raise value
SpinnmanIOException: IO Error: no such table: configuration_parameters

=
Getting provenance data from application graph
|0%                          50%                         100%|
 ============================================================
[pacman.executor.pacman_algorithm_executor][INFO] 2020-02-20 15:01:37,106: Time 0:00:00.003114 taken by GraphProvenanceGatherer
[spinn_front_end_common.interface.abstract_spinnaker_base][INFO] 2020-02-20 15:01:37,107: Waiting for stop request
[INFO] [1582207302.036078, 4.487000]: [Client 1] Subscribed to /monitor/spike_recorder
[rospy.internal][INFO] 2020-02-20 15:01:42,052: topic[/monitor/spike_recorder] adding connection to [/rosbridge_websocket], count 0

```

**Comment by alan-stokes** [comment]
can you confirm if the database has been written? as my looking into the src code implies it wouldn't crash unless the table didn't exist in the first place.

**Comment by rowleya** [comment]
I think that in the latest release code the database was not configured correctly when certain features are present, resulting in a failure to write the database.  I think that this is fixed in the master code.  A workaround is to add a config option to your ```.spynnaker.cfg``` file:
```
[Database]
create_database = True
```

This will force the creation of the database and should get rid of the second error.  If you are getting the first error at the same time, it might have been because the reading of the database didn't work correctly (due to the first error), so the protocol is out of sync.  In that case, the above workaround should fix that error too.

**Comment by bjuergens** [comment]
Thank you for your replies. 

I did some more digging and noticed, that right before the "no such table"-error, it says 
> [spinn_front_end_common.utilities.database.database_connection][INFO] 2020-02-20 15:01:37,104: database is at ��

So the error happens because it tries to open a db at an invalid path. The path is read from a UDP package. So both errors can be explained with unexpected UDP packages. 

I added some extensive logging and found that the DatabaseConnect, that is responsible for the error is created here: https://github.com/SpiNNakerManchester/sPyNNaker8/blob/1697bea0859a6f6cef83c90df3f512403c4559ba/spynnaker8/external_devices/__init__.py#L182

**Comment by rowleya** [comment]
OK, that makes sense - I don't think we had considered the case of multiple runs of different networks from the same process.

**Comment by bjuergens** [comment]
Thanks.

I'm closing this, since my question has been answered and a downstream-workaround to my downstream-issue has been implemented. Feel free to reopen, if you want to address the problem in your code, too (though I'd recommend to open a separate issue for that)
